services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Amt\AmtPinecone\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Amt\AmtPinecone\Command\IndexToPineconeCommand:
    tags:
      -
        name: console.command
        command: 'amt-pinecone:indexing-to-pinecone'
        description: 'Indexing records to the Pinecone API'
        schedulable: true
