services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Amt\AmtPinecone\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Amt\AmtPinecone\Command\IndexToPineconeCommand:
    tags:
      -
        name: console.command
        command: 'amt-pinecone:indexing-to-pinecone'
        description: 'Indexing records to the Pinecone API'
        schedulable: true

  Amt\AmtPinecone\Command\PineconeDataIntegrityCommand:
    tags:
      -
        name: console.command
        command: 'amt-pinecone:data-integrity'
        description: 'Data integrity - removes from index deleted records'
        schedulable: true

  Amt\AmtPinecone\Domain\Repository\PineconeRepository:
    arguments:
      $pineconeRepositoryQueryBuilder: '@queryBuilder.tx_amt_pinecone_pineconeindex'

  queryBuilder.tx_amt_pinecone_pineconeindex:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
        - '@TYPO3\CMS\Core\Database\ConnectionPool'
        - 'getQueryBuilderForTable'
    arguments:
        - 'tx_amt_pinecone_pineconeindex'

  Amt\AmtPinecone\Domain\Repository\PineconeConfigIndexRepository:
    arguments:
      $pineconeConfigIndexRepositoryQueryBuilder: '@queryBuilder.tx_amt_pinecone_configindex'

  queryBuilder.tx_amt_pinecone_configindex:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_amt_pinecone_configindex'

  Amt\AmtPinecone\ViewHelpers\PineconeSearchViewHelper:
    calls:
      - method: 'injectPineconeSearchService'
        arguments:
          $pineconeSearchService: '@Amt\AmtPinecone\Service\PineconeSearchService'
    public: true
